server {
    listen 80;
    listen [::]:80;
    server_name rajko.cloud www.rajko.cloud;

    root /var/www/rajko-cloud;
    index index.html;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ /\. {
        deny all;
    }
}
